..\..\env\Scripts\python.exe ..\..\manage.py makemigrations contact
..\..\env\Scripts\python.exe ..\..\manage.py makemigrations department
..\..\env\Scripts\python.exe ..\..\manage.py makemigrations environment
..\..\env\Scripts\python.exe ..\..\manage.py makemigrations asset
..\..\env\Scripts\python.exe ..\..\manage.py makemigrations device
..\..\env\Scripts\python.exe ..\..\manage.py makemigrations network
..\..\env\Scripts\python.exe ..\..\manage.py makemigrations respool
..\..\env\Scripts\python.exe ..\..\manage.py makemigrations vmware
..\..\env\Scripts\python.exe ..\..\manage.py makemigrations application